server:
  port: 8081
spring:
  application:
    name: bluemoonpay
  datasource:
    url: jdbc:postgresql://localhost:5432/bluemoon_payment
    username: postgres
    password: NewStrongPassword123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
vault:
  master-key: NqcfbJG1zkOfBsNF/wPmlLA7aaOvh9RCHTYYgY/9A2Q=